### ISSUE TITLE
[archlinux] com.deepin.daemon.Network generates repeated errors

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/dde-daemon#24]
I have several tun devices that could be the cause.

Repeated error messages:

```
Jul 16 23:30:51 flygon.felixc.at daemon/network[12794]: nm_custom_type.go:71: unknown device type 16
                                                          ->  manager_device.go:243
                                                          ->  manager_device.go:69
                                                          ->  manager.go:122
                                                          ->  main.go:55
                                                          ->  module.go:51
                                                          ->  module.go:54
                                                          ->  module.go:66
                                                          ->  loader.go:152
                                                          ->  global.go:50
                                                          ->  daemon.go:161
                                                          ->  daemon.go:170
                                                          ->  main.go:83
                                                          ->  proc.go:188
                                                          ->  asm_amd64.s:1998
```

And crashes:

```
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]: panic: runtime error: cgo argument has Go pointer to Go pointer
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]: goroutine 1 [running]:
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]: panic(0xe07a00, 0xc82042cb90)
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]:         /usr/lib/go/src/runtime/panic.go:481 +0x3e6
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]: gir/gio-2%2e0._cgoCheckPointer0(0xc5ec20, 0xc8201a8190, 0x0, 0x0, 0x0, 0xc28080)
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]:         ??:0 +0x4d
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]: gir/gio-2%2e0.(*VolumeImpl).Mount(0xc8200bc2d0, 0xc800000000, 0x0, 0x0, 0x0, 0x0, 0xc8207a56b0)
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]:         /build/deepin-daemon/src/build/src/gir/gio-2.0/gio.go:11165 +0x29e
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]: pkg.deepin.io/dde/daemon/mounts.(*Manager).mountVolume(0xc8203aa7d0, 0xc82041a030, 0x24, 0xc8204cb8a0)
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]:         /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/mounts/ifc.go:155 +0x3df
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]: pkg.deepin.io/dde/daemon/mounts.(*Manager).Mount(0xc8203aa7d0, 0xc82041a030, 0x24, 0x0, 0x0)
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]:         /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/mounts/ifc.go:62 +0x2d7
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]: pkg.deepin.io/dde/daemon/mounts.(*Manager).init(0xc8203aa7d0)
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]:         /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/mounts/manager.go:63 +0x2fa
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]: pkg.deepin.io/dde/daemon/mounts.newManager(0x1e)
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]:         /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/mounts/manager.go:50 +0xbb
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]: pkg.deepin.io/dde/daemon/mounts.(*Daemon).Start(0xc8200bc0f0, 0x0, 0x0)
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]:         /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/mounts/mounts.go:46 +0x5e
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]: pkg.deepin.io/dde/daemon/loader.(ModuleImpl).Start-fm(0x0, 0x0)
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]:         /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/loader/module.go:51 +0x40
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]: pkg.deepin.io/dde/daemon/loader.(*ModuleBase).doEnable(0xc8200c4a20, 0x1207c1401, 0x0, 0x0)
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]:         /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/loader/module.go:54 +0xd3
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]: pkg.deepin.io/dde/daemon/loader.(*ModuleBase).Enable(0xc8200c4a20, 0xc82a8d4a01, 0x0, 0x0)
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]:         /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/loader/module.go:66 +0x157
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]: pkg.deepin.io/dde/daemon/loader.(*Loader).EnableModules(0xc8200d0880, 0xc82019a900, 0xf, 0x10, 0x16e7350, 0x0, 0x0, 0x1, 0x0, 0x0)
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]:         /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/loader/loader.go:152 +0x48a
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]: pkg.deepin.io/dde/daemon/loader.EnableModules(0xc82019a900, 0xf, 0x10, 0x16e7350, 0x0, 0x0, 0x1, 0x0, 0x0)
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]:         /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/loader/global.go:50 +0x8e
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]: main.(*SessionDaemon).defaultAction(0xc82000eb00)
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]:         /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/bin/dde-session-daemon/daemon.go:161 +0x104
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]: main.(*SessionDaemon).execDefaultAction(0xc82000eb00)
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]:         /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/bin/dde-session-daemon/daemon.go:170 +0x21
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]: main.main()
Jul 16 23:30:52 flygon.felixc.at com.deepin.daemon.Network[9833]:         /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/bin/dde-session-daemon/main.go:83 +0x136c
```

**Comment by fasheng** [comment]
NetworkManager 1.2+ issue, will try to fix it about one month later.



2016年7月16日 23:33, 23:33，在 Felix Yan <notifications@github.com> 已写:

**Comment by fasheng** [comment]
The crash issue see here please https://github.com/linuxdeepin/dde-daemon/issues/26

**Comment by fasheng** [comment]
dde-daemon 3.0.21 will fix this, and the support for networkmanager 1.4.1 is on the way

**Comment by manateelazycat** [comment]
@fasheng This issue can close now?

**Comment by felixonmars** [comment]
@manateelazycat It's still an issue with networkmanager 1.6

**Comment by jouyouyun** [comment]
@felixonmars is the issue exists now?

**Comment by felixonmars** [comment]
Still persists here.

**Comment by jouyouyun** [comment]
Ignore the error messages. 
Is the dde-session-daemon crashed now?

**Comment by jouyouyun** [comment]
@felixonmars

**Comment by felixonmars** [comment]
No it doesn't crash. The error messages are still present, though.

**Comment by jouyouyun** [comment]
The error messages is normal.
