### ISSUE TITLE
New crash in dde-daemon

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/dde-daemon#31]
The patch in BurntSushi/xgbutil#35 is already applied, so it seems like a different issue:

```
fatal error: concurrent map writes

goroutine 3038 [running]:
runtime.throw(0x996b99, 0x15)
        /usr/lib/go/src/runtime/panic.go:566 +0x95 fp=0xc4209ad5a0 sp=0xc4209ad580
runtime.mapassign1(0x903540, 0xc420245200, 0xc4209ad6d8, 0xc4209ad760)
        /usr/lib/go/src/runtime/hashmap.go:458 +0x8ef fp=0xc4209ad688 sp=0xc4209ad5a0
pkg.deepin.io/dde/daemon/launcher.(*Launcher).itemChangedHandler(0xc4201ee000, 0xc4201313e0, 0xc4202ac900, 0x40, 0xc420245200)
        /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/launcher/launcher.go:328 +0x649 fp=0xc4209ad798 sp=0xc4209ad688
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4209ad7a0 sp=0xc4209ad798
created by pkg.deepin.io/dde/daemon/launcher.(*Launcher).eventHandler
        /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/launcher/launcher.go:411 +0x1df

goroutine 1 [chan receive, 60 minutes]:
main.runMainLoop()
        /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/bin/dde-session-initializer/main.go:50 +0x536
main.main()
        /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/bin/dde-session-initializer/main.go:98 +0x29c

goroutine 17 [syscall, 60 minutes, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [syscall, 60 minutes]:
os/signal.signal_recv(0x0)
        /usr/lib/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /usr/lib/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [IO wait]:
net.runtime_pollWait(0x7fb8bd2e0a80, 0x72, 0xc42031d6c8)
        /usr/lib/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420156370, 0x72, 0xc42031d808, 0xc420010128)
        /usr/lib/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420156370, 0xe25720, 0xc420010128)
        /usr/lib/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).readMsg(0xc420156310, 0xc4203f12b0, 0x10, 0x10, 0xc420389220, 0x1000, 0x1000, 0xffffffffffffffff, 0x0, 0x0, ...)
        /usr/lib/go/src/net/fd_unix.go:297 +0x243
net.(*UnixConn).readMsg(0xc420036398, 0xc4203f12b0, 0x10, 0x10, 0xc420389220, 0x1000, 0x1000, 0xc4203f0ee3, 0xc420338000, 0x0, ...)
        /usr/lib/go/src/net/unixsock_posix.go:111 +0x91
net.(*UnixConn).ReadMsgUnix(0xc420036398, 0xc4203f12b0, 0x10, 0x10, 0xc420389220, 0x1000, 0x1000, 0x0, 0x0, 0xc4203f111c, ...)
        /usr/lib/go/src/net/unixsock.go:127 +0xaa
pkg.deepin.io/lib/dbus.(*oobReader).Read(0xc420389200, 0xc4203f12b0, 0x10, 0x10, 0x1020, 0xc420389200, 0x0)
        /build/deepin-daemon/src/build/src/pkg.deepin.io/lib/dbus/transport_unix.go:28 +0x95
io.ReadAtLeast(0xe24920, 0xc420389200, 0xc4203f12b0, 0x10, 0x10, 0x10, 0x934620, 0x8cdb01, 0xc420389200)
        /usr/lib/go/src/io/io.go:307 +0xa4
io.ReadFull(0xe24920, 0xc420389200, 0xc4203f12b0, 0x10, 0x10, 0x31, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:325 +0x58
pkg.deepin.io/lib/dbus.(*unixTransport).ReadMessage(0xc420011b50, 0x9ca310, 0xc42013b320, 0xc420158ff0)
        /build/deepin-daemon/src/build/src/pkg.deepin.io/lib/dbus/transport_unix.go:88 +0x15b
pkg.deepin.io/lib/dbus.(*Conn).inWorker(0xc42013b320)
        /build/deepin-daemon/src/build/src/pkg.deepin.io/lib/dbus/conn.go:255 +0x4b
created by pkg.deepin.io/lib/dbus.(*Conn).Auth
        /build/deepin-daemon/src/build/src/pkg.deepin.io/lib/dbus/auth.go:129 +0x732

goroutine 7 [chan receive]:
pkg.deepin.io/lib/dbus.(*Conn).outWorker(0xc42013b320)
        /build/deepin-daemon/src/build/src/pkg.deepin.io/lib/dbus/conn.go:377 +0x5d
created by pkg.deepin.io/lib/dbus.(*Conn).Auth
        /build/deepin-daemon/src/build/src/pkg.deepin.io/lib/dbus/auth.go:130 +0x757

goroutine 18 [chan receive, 60 minutes]:
pkg.deepin.io/lib/profile.(*Config).Start.func4(0xc42017e0c0)
        /build/deepin-daemon/src/build/src/pkg.deepin.io/lib/profile/profile.go:157 +0xb6
created by pkg.deepin.io/lib/profile.(*Config).Start
        /build/deepin-daemon/src/build/src/pkg.deepin.io/lib/profile/profile.go:162 +0x118

goroutine 8 [select, 60 minutes, locked to thread]:
runtime.gopark(0x9ca800, 0x0, 0x98a595, 0x6, 0x18, 0x2)
        /usr/lib/go/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc420034f30, 0x0, 0x18)
        /usr/lib/go/src/runtime/select.go:423 +0x11d9
runtime.selectgo(0xc420034f30)
        /usr/lib/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
        /usr/lib/go/src/runtime/signal1_unix.go:304 +0x2f3
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 44 [syscall, 60 minutes, locked to thread]:
gir/glib-2%2e0._Cfunc__run()
        ??:0 +0x41
gir/glib-2%2e0.StartLoop()
        /build/deepin-daemon/src/build/src/gir/glib-2.0/misc.go:13 +0x14
created by main.runMainLoop
        /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/bin/dde-session-initializer/main.go:47 +0x45c

goroutine 50 [IO wait]:
net.runtime_pollWait(0x7fb8bd2e09c0, 0x72, 0xc4204376d8)
        /usr/lib/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4202886f0, 0x72, 0xc420437818, 0xc420010128)
        /usr/lib/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4202886f0, 0xe25720, 0xc420010128)
        /usr/lib/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).readMsg(0xc420288690, 0xc4203f0510, 0x10, 0x10, 0xc4200d2420, 0x1000, 0x1000, 0xffffffffffffffff, 0x0, 0x0, ...)
        /usr/lib/go/src/net/fd_unix.go:297 +0x243
net.(*UnixConn).readMsg(0xc420266330, 0xc4203f0510, 0x10, 0x10, 0xc4200d2420, 0x1000, 0x1000, 0xc4203f025b, 0xc420021730, 0x0, ...)
        /usr/lib/go/src/net/unixsock_posix.go:111 +0x91
net.(*UnixConn).ReadMsgUnix(0xc420266330, 0xc4203f0510, 0x10, 0x10, 0xc4200d2420, 0x1000, 0x1000, 0x0, 0x0, 0xc4203f03f8, ...)
        /usr/lib/go/src/net/unixsock.go:127 +0xaa
pkg.deepin.io/lib/dbus.(*oobReader).Read(0xc4200d2400, 0xc4203f0510, 0x10, 0x10, 0x1020, 0xc4200d2400, 0x0)
        /build/deepin-daemon/src/build/src/pkg.deepin.io/lib/dbus/transport_unix.go:28 +0x95
io.ReadAtLeast(0xe24920, 0xc4200d2400, 0xc4203f0510, 0x10, 0x10, 0x10, 0x934620, 0x8cdb01, 0xc4200d2400)
        /usr/lib/go/src/io/io.go:307 +0xa4
io.ReadFull(0xe24920, 0xc4200d2400, 0xc4203f0510, 0x10, 0x10, 0x49, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:325 +0x58
pkg.deepin.io/lib/dbus.(*unixTransport).ReadMessage(0xc420402df0, 0xc42035de30, 0xc420437d94, 0xe256a0)
        /build/deepin-daemon/src/build/src/pkg.deepin.io/lib/dbus/transport_unix.go:88 +0x15b
pkg.deepin.io/lib/dbus.(*Conn).inWorker(0xc4202a07e0)
        /build/deepin-daemon/src/build/src/pkg.deepin.io/lib/dbus/conn.go:255 +0x4b
created by pkg.deepin.io/lib/dbus.(*Conn).Auth
        /build/deepin-daemon/src/build/src/pkg.deepin.io/lib/dbus/auth.go:129 +0x732

goroutine 100 [chan receive]:
github.com/BurntSushi/xgb.(*Conn).sendRequests(0xc4202c2e70)
        /build/deepin-daemon/src/build/src/github.com/BurntSushi/xgb/xgb.go:328 +0x88
created by github.com/BurntSushi/xgb.postNewConn
        /build/deepin-daemon/src/build/src/github.com/BurntSushi/xgb/xgb.go:132 +0x237

goroutine 43 [chan receive]:
github.com/BurntSushi/xgb.(*Conn).WaitForEvent(0xc4202c2e70, 0xe26de0, 0xc420302a20, 0xc420a4bed0, 0x1)
        /build/deepin-daemon/src/build/src/github.com/BurntSushi/xgb/xgb.go:540 +0x5b
pkg.deepin.io/dde/daemon/trayicon.(*TrayManager).startListener(0xc4201a3540)
        /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/trayicon/traymanager.go:206 +0x95
created by pkg.deepin.io/dde/daemon/trayicon.(*TrayManager).init
        /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/trayicon/traymanager.go:72 +0xb2

goroutine 101 [IO wait]:
net.runtime_pollWait(0x7fb8bd2e0840, 0x72, 0x13)
        /usr/lib/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420021db0, 0x72, 0xc420276c28, 0xc420010128)
        /usr/lib/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420021db0, 0xe25720, 0xc420010128)
        /usr/lib/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc420021d50, 0xc4202862a0, 0x20, 0x20, 0x0, 0xe25720, 0xc420010128)
        /usr/lib/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc420252150, 0xc4202862a0, 0x20, 0x20, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/net.go:173 +0x70
io.ReadAtLeast(0x7fb8a8879078, 0xc420252150, 0xc4202862a0, 0x20, 0x20, 0x20, 0x971aa0, 0x798100, 0x7fb8a8879078)
        /usr/lib/go/src/io/io.go:307 +0xa4
io.ReadFull(0x7fb8a8879078, 0xc420252150, 0xc4202862a0, 0x20, 0x20, 0x20, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:325 +0x58
github.com/BurntSushi/xgb.(*Conn).readResponses(0xc4202c2e70)
        /build/deepin-daemon/src/build/src/github.com/BurntSushi/xgb/xgb.go:402 +0x1a9
created by github.com/BurntSushi/xgb.postNewConn
        /build/deepin-daemon/src/build/src/github.com/BurntSushi/xgb/xgb.go:133 +0x259

goroutine 98 [chan send]:
github.com/BurntSushi/xgb.(*Conn).generateXIds(0xc4202c2e70)
        /build/deepin-daemon/src/build/src/github.com/BurntSushi/xgb/xgb.go:256 +0xe0
created by github.com/BurntSushi/xgb.postNewConn
        /build/deepin-daemon/src/build/src/github.com/BurntSushi/xgb/xgb.go:130 +0x1f3

goroutine 99 [chan send]:
github.com/BurntSushi/xgb.(*Conn).generateSeqIds(0xc4202c2e70)
        /build/deepin-daemon/src/build/src/github.com/BurntSushi/xgb/xgb.go:278 +0x82
created by github.com/BurntSushi/xgb.postNewConn
        /build/deepin-daemon/src/build/src/github.com/BurntSushi/xgb/xgb.go:131 +0x215

goroutine 51 [chan receive]:
pkg.deepin.io/lib/dbus.(*Conn).outWorker(0xc4202a07e0)
        /build/deepin-daemon/src/build/src/pkg.deepin.io/lib/dbus/conn.go:377 +0x5d
created by pkg.deepin.io/lib/dbus.(*Conn).Auth
        /build/deepin-daemon/src/build/src/pkg.deepin.io/lib/dbus/auth.go:130 +0x757

goroutine 52 [syscall]:
syscall.Syscall(0x0, 0x16, 0xc42047dee0, 0x10000, 0x0, 0xc42047de00, 0x51e5c5)
        /usr/lib/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x16, 0xc42047dee0, 0x10000, 0x10000, 0x0, 0x6b2200, 0x0)
        /usr/lib/go/src/syscall/zsyscall_linux_amd64.go:783 +0x55
syscall.Read(0x16, 0xc42047dee0, 0x10000, 0x10000, 0xc4204bc140, 0xc42047de01, 0x1a)
        /usr/lib/go/src/syscall/syscall_unix.go:161 +0x49
github.com/howeyc/fsnotify.(*Watcher).readEvents(0xc4202b1740)
        /build/deepin-daemon/src/build/src/github.com/howeyc/fsnotify/fsnotify_linux.go:219 +0xc7
created by github.com/howeyc/fsnotify.NewWatcher
        /build/deepin-daemon/src/build/src/github.com/howeyc/fsnotify/fsnotify_linux.go:126 +0x382

goroutine 53 [chan receive]:
github.com/howeyc/fsnotify.(*Watcher).purgeEvents(0xc4202b1740)
        /build/deepin-daemon/src/build/src/github.com/howeyc/fsnotify/fsnotify.go:21 +0x57
created by github.com/howeyc/fsnotify.NewWatcher
        /build/deepin-daemon/src/build/src/github.com/howeyc/fsnotify/fsnotify_linux.go:127 +0x3a4

goroutine 54 [select]:
pkg.deepin.io/dde/daemon/launcher.(*Launcher).eventHandler(0xc4201ee000, 0xc4202b1740)
        /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/launcher/launcher.go:398 +0x330
created by pkg.deepin.io/dde/daemon/launcher.(*Launcher).listenItemChanged
        /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/launcher/launcher.go:457 +0x229

goroutine 55 [chan receive, 60 minutes]:
pkg.deepin.io/lib/dbus.(*signalChannel).run(0xc42042c630)
        /build/deepin-daemon/src/build/src/pkg.deepin.io/lib/dbus/signal_channel.go:61 +0x1a9
created by pkg.deepin.io/lib/dbus.newSignalChannel
        /build/deepin-daemon/src/build/src/pkg.deepin.io/lib/dbus/signal_channel.go:23 +0x136

goroutine 56 [chan receive, 60 minutes]:
dbus/com/deepin/store/api.(*DStoreDesktop).ConnectNewDesktopAdded.func1(0xc4202b1800, 0xc4203b3f80, 0xc420454070)
        /build/deepin-daemon/src/build/src/dbus/com/deepin/store/api/deepin-store-dbus.go:104 +0x7c
created by dbus/com/deepin/store/api.(*DStoreDesktop).ConnectNewDesktopAdded
        /build/deepin-daemon/src/build/src/dbus/com/deepin/store/api/deepin-store-dbus.go:117 +0x6a

goroutine 66 [chan send, 60 minutes]:
github.com/BurntSushi/xgb.(*Conn).generateXIds(0xc4202438c0)
        /build/deepin-daemon/src/build/src/github.com/BurntSushi/xgb/xgb.go:256 +0xe0
created by github.com/BurntSushi/xgb.postNewConn
        /build/deepin-daemon/src/build/src/github.com/BurntSushi/xgb/xgb.go:130 +0x1f3

goroutine 67 [chan send]:
github.com/BurntSushi/xgb.(*Conn).generateSeqIds(0xc4202438c0)
        /build/deepin-daemon/src/build/src/github.com/BurntSushi/xgb/xgb.go:278 +0x82
created by github.com/BurntSushi/xgb.postNewConn
        /build/deepin-daemon/src/build/src/github.com/BurntSushi/xgb/xgb.go:131 +0x215

goroutine 68 [chan receive]:
github.com/BurntSushi/xgb.(*Conn).sendRequests(0xc4202438c0)
        /build/deepin-daemon/src/build/src/github.com/BurntSushi/xgb/xgb.go:328 +0x88
created by github.com/BurntSushi/xgb.postNewConn
        /build/deepin-daemon/src/build/src/github.com/BurntSushi/xgb/xgb.go:132 +0x237

goroutine 69 [IO wait]:
net.runtime_pollWait(0x7fb8bd2e0900, 0x72, 0x17)
        /usr/lib/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc42026cca0, 0x72, 0xc4201b3c28, 0xc420010128)
        /usr/lib/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc42026cca0, 0xe25720, 0xc420010128)
        /usr/lib/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc42026cc40, 0xc420131380, 0x20, 0x20, 0x0, 0xe25720, 0xc420010128)
        /usr/lib/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc420252118, 0xc420131380, 0x20, 0x20, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/net.go:173 +0x70
io.ReadAtLeast(0x7fb8a8879078, 0xc420252118, 0xc420131380, 0x20, 0x20, 0x20, 0x971aa0, 0x798100, 0x7fb8a8879078)
        /usr/lib/go/src/io/io.go:307 +0xa4
io.ReadFull(0x7fb8a8879078, 0xc420252118, 0xc420131380, 0x20, 0x20, 0x20, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:325 +0x58
github.com/BurntSushi/xgb.(*Conn).readResponses(0xc4202438c0)
        /build/deepin-daemon/src/build/src/github.com/BurntSushi/xgb/xgb.go:402 +0x1a9
created by github.com/BurntSushi/xgb.postNewConn
        /build/deepin-daemon/src/build/src/github.com/BurntSushi/xgb/xgb.go:133 +0x259

goroutine 89 [chan receive, 25 minutes]:
pkg.deepin.io/lib/dbus.(*signalChannel).run(0xc4203bade0)
        /build/deepin-daemon/src/build/src/pkg.deepin.io/lib/dbus/signal_channel.go:61 +0x1a9
created by pkg.deepin.io/lib/dbus.newSignalChannel
        /build/deepin-daemon/src/build/src/pkg.deepin.io/lib/dbus/signal_channel.go:23 +0x136

goroutine 90 [chan receive, 25 minutes]:
dbus/com/deepin/dde/daemon/launcher.(*Launcher).ConnectItemChanged.func1(0xc42017e480, 0xc4203a2b00, 0xc4203d9400)
        /build/deepin-daemon/src/build/src/dbus/com/deepin/dde/daemon/launcher/launcher-0.go:210 +0x81
created by dbus/com/deepin/dde/daemon/launcher.(*Launcher).ConnectItemChanged
        /build/deepin-daemon/src/build/src/dbus/com/deepin/dde/daemon/launcher/launcher-0.go:226 +0x6a

goroutine 91 [chan receive]:
github.com/BurntSushi/xgb.(*Conn).WaitForEvent(0xc4202438c0, 0x0, 0x0, 0x0, 0x0)
        /build/deepin-daemon/src/build/src/github.com/BurntSushi/xgb/xgb.go:540 +0x5b
github.com/BurntSushi/xgbutil/xevent.Read(0xc42034a140, 0x1)
        /build/deepin-daemon/src/build/src/github.com/BurntSushi/xgbutil/xevent/eventloop.go:25 +0x46
github.com/BurntSushi/xgbutil/xevent.mainEventLoop(0xc42034a140, 0x0, 0x0, 0x0)
        /build/deepin-daemon/src/build/src/github.com/BurntSushi/xgbutil/xevent/eventloop.go:105 +0x3c
github.com/BurntSushi/xgbutil/xevent.Main(0xc42034a140)
        /build/deepin-daemon/src/build/src/github.com/BurntSushi/xgbutil/xevent/eventloop.go:52 +0x46
created by pkg.deepin.io/dde/daemon/dock.(*Daemon).Start
        /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/dock/main.go:81 +0x2cb

goroutine 3040 [chan receive]:
pkg.deepin.io/dde/daemon/launcher.(*Launcher).itemChangedHandler.func3(0xc420245200, 0xc4202ac940, 0x40, 0xc4201ee000)
        /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/launcher/launcher.go:370 +0xc4
created by pkg.deepin.io/dde/daemon/launcher.(*Launcher).itemChangedHandler
        /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/launcher/launcher.go:378 +0x222

goroutine 2980 [chan receive (nil chan), 1 minutes]:
pkg.deepin.io/dde/daemon/launcher.(*Launcher).itemChangedHandler.func2(0xc420245200, 0xc42041e180, 0x24)
        /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/launcher/launcher.go:363 +0x274
created by pkg.deepin.io/dde/daemon/launcher.(*Launcher).itemChangedHandler
        /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/launcher/launcher.go:365 +0x2d4

goroutine 2929 [chan send (nil chan), 1 minutes]:
pkg.deepin.io/dde/daemon/launcher.(*Launcher).itemChangedHandler(0xc4201ee000, 0xc42000df20, 0xc42041e180, 0x24, 0xc420245200)
        /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/launcher/launcher.go:366 +0x35d
created by pkg.deepin.io/dde/daemon/launcher.(*Launcher).eventHandler
        /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/launcher/launcher.go:411 +0x1df

goroutine 2979 [chan receive, 1 minutes]:
pkg.deepin.io/dde/daemon/launcher.(*Launcher).itemChangedHandler.func3(0xc420245200, 0xc42041e240, 0x24, 0xc4201ee000)
        /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/launcher/launcher.go:370 +0xc4
created by pkg.deepin.io/dde/daemon/launcher.(*Launcher).itemChangedHandler
        /build/deepin-daemon/src/dde-daemon/gopath/src/pkg.deepin.io/dde/daemon/launcher/launcher.go:378 +0x222
```

**Comment by fasheng** [comment]
@electricface Looks the same issue with https://github.com/golang/go/issues/16778 for the smarter GC strategy under golang 1.7 :joy:

**Comment by electricface** [comment]
在新的launcher模块中解决吧 https://cr.deepin.io/#/c/15991/

**Comment by electricface** [comment]
问题已经解决了

**Comment by felixonmars** [comment]
多谢！
