### ISSUE TITLE
(Arch Deepin) Dock and control center freezes due to VPN

### ISSUE THREAD

**Issue by lupujo** [linuxdeepin/dde-daemon#53]
With Arch Deepin, the system boots with a frozen Dock when VPN connection is set to auto-connect and connection is unsuccessful. Disabling NetworkManager service and rebooting allows the system to boot properly.

2 snippets from the logs are attached below.

_com.deepin.daemon.Zone:_
```
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: panic: you should call *proxy.Object.InitSignalExt() first
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: goroutine 57 [running]:
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: pkg.deepin.io/lib/dbusutil/proxy.(*Object).checkSignalExt(0xc420233c50)
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]:         /usr/share/gocode/src/pkg.deepin.io/lib/dbusutil/proxy/object.go:164 +0xcf
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: pkg.deepin.io/lib/dbusutil/proxy.(*Object).ConnectSignal_(0xc420233c50, 0xc420582460, 0x9d, 0xc4207160c0, 0xc42001fdf0, 0x0, 0x0, 0x0)
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]:         /usr/share/gocode/src/pkg.deepin.io/lib/dbusutil/proxy/object.go:218 +0x87
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: github.com/linuxdeepin/go-dbus-factory/org%2efreedesktop%2enetworkmanager.(*manager).ConnectStateChanged(0xc420233c50, 0xc420350aa0, 0x55fb45eaeb16, 0x5, 0xc4205d7d00)
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]:         /usr/share/gocode/src/github.com/linuxdeepin/go-dbus-factory/org.freedesktop.networkmanager/auto.go:1344 +0x306
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: pkg.deepin.io/dde/daemon/network.nmRunOnceUtilNetworkAvailable(0xc420350980)
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/utils_dbus_nm.go:1548 +0x105
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: pkg.deepin.io/dde/daemon/network.(*switchHandler).activateVpnConnection(0xc4204fa770, 0xc4206c0180, 0x24)
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/manager_switch.go:401 +0x8d
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: pkg.deepin.io/dde/daemon/network.(*switchHandler).restoreVpnConnectionState(0xc4204fa770, 0xc4206c0180, 0x24, 0xc42001f8d0, 0x1)
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/manager_switch.go:390 +0x94
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: pkg.deepin.io/dde/daemon/network.(*switchHandler).enableVpn(0xc4204fa770, 0xc42001f401)
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/manager_switch.go:283 +0xbd
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: pkg.deepin.io/dde/daemon/network.(*switchHandler).initPropVpnEnabled(0xc4204fa770)
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/manager_switch.go:269 +0x7b
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: pkg.deepin.io/dde/daemon/network.(*switchHandler).init(0xc4204fa770)
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/manager_switch.go:71 +0x65
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: pkg.deepin.io/dde/daemon/network.newSwitchHandler(0xc42053c000, 0x55fb46465d90)
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/manager_switch.go:39 +0x79
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: pkg.deepin.io/dde/daemon/network.(*Manager).init(0xc420188900)
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/manager.go:183 +0x17b
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: pkg.deepin.io/dde/daemon/network.(*Daemon).Start.func1()
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/maiAug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: panic: you should call *proxy.Object.InitSignalExt() first
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: goroutine 57 [running]:
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: pkg.deepin.io/lib/dbusutil/proxy.(*Object).checkSignalExt(0xc420233c50)
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]:         /usr/share/gocode/src/pkg.deepin.io/lib/dbusutil/proxy/object.go:164 +0xcf
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: pkg.deepin.io/lib/dbusutil/proxy.(*Object).ConnectSignal_(0xc420233c50, 0xc420582460, 0x9d, 0xc4207160c0, 0xc42001fdf0, 0x0, 0x0, 0x0)
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]:         /usr/share/gocode/src/pkg.deepin.io/lib/dbusutil/proxy/object.go:218 +0x87
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: github.com/linuxdeepin/go-dbus-factory/org%2efreedesktop%2enetworkmanager.(*manager).ConnectStateChanged(0xc420233c50, 0xc420350aa0, 0x55fb45eaeb16, 0x5, 0xc4205d7d00)
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]:         /usr/share/gocode/src/github.com/linuxdeepin/go-dbus-factory/org.freedesktop.networkmanager/auto.go:1344 +0x306
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: pkg.deepin.io/dde/daemon/network.nmRunOnceUtilNetworkAvailable(0xc420350980)
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/utils_dbus_nm.go:1548 +0x105
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: pkg.deepin.io/dde/daemon/network.(*switchHandler).activateVpnConnection(0xc4204fa770, 0xc4206c0180, 0x24)
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/manager_switch.go:401 +0x8d
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: pkg.deepin.io/dde/daemon/network.(*switchHandler).restoreVpnConnectionState(0xc4204fa770, 0xc4206c0180, 0x24, 0xc42001f8d0, 0x1)
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/manager_switch.go:390 +0x94
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: pkg.deepin.io/dde/daemon/network.(*switchHandler).enableVpn(0xc4204fa770, 0xc42001f401)
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/manager_switch.go:283 +0xbd
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: pkg.deepin.io/dde/daemon/network.(*switchHandler).initPropVpnEnabled(0xc4204fa770)
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/manager_switch.go:269 +0x7b
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: pkg.deepin.io/dde/daemon/network.(*switchHandler).init(0xc4204fa770)
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/manager_switch.go:71 +0x65
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: pkg.deepin.io/dde/daemon/network.newSwitchHandler(0xc42053c000, 0x55fb46465d90)
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/manager_switch.go:39 +0x79
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: pkg.deepin.io/dde/daemon/network.(*Manager).init(0xc420188900)
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/manager.go:183 +0x17b
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: pkg.deepin.io/dde/daemon/network.(*Daemon).Start.func1()
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/main.go:91 +0x2f
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]: created by pkg.deepin.io/dde/daemon/network.(*Daemon).Start
Aug 04 07:06:53 myhostname com.deepin.daemon.Zone[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/main.go:90 +0x4f8
Aug 04 07:06:53 myhostname dbus-daemon[557]: [session uid=1000 pid=557] Activated service 'com.deepin.daemon.Zone' failed: Process com.deepin.daemon.Zone exited with status 2
```

_com.deepin.dde.daemon.Dock:_
```
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]: panic: you should call *proxy.Object.InitSignalExt() first
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]: goroutine 85 [running]:
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]: pkg.deepin.io/lib/dbusutil/proxy.(*Object).checkSignalExt(0xc42025a390)
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]:         /usr/share/gocode/src/pkg.deepin.io/lib/dbusutil/proxy/object.go:164 +0xcf
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]: pkg.deepin.io/lib/dbusutil/proxy.(*Object).ConnectSignal_(0xc42025a390, 0xc4205a0280, 0x9d, 0xc42025a750, 0xc420728b40, 0x0, 0x0, 0x0)
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]:         /usr/share/gocode/src/pkg.deepin.io/lib/dbusutil/proxy/object.go:218 +0x87
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]: github.com/linuxdeepin/go-dbus-factory/org%2efreedesktop%2enetworkmanager.(*manager).ConnectStateChanged(0xc42025a390, 0xc420194ca0, 0x55e0d2f9fb16, 0x5, 0xc420517d00)
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]:         /usr/share/gocode/src/github.com/linuxdeepin/go-dbus-factory/org.freedesktop.networkmanager/auto.go:1344 +0x306
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]: pkg.deepin.io/dde/daemon/network.nmRunOnceUtilNetworkAvailable(0xc420194b80)
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/utils_dbus_nm.go:1548 +0x105
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]: pkg.deepin.io/dde/daemon/network.(*switchHandler).activateVpnConnection(0xc4204b41d0, 0xc420029e30, 0x24)
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/manager_switch.go:401 +0x8d
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]: pkg.deepin.io/dde/daemon/network.(*switchHandler).restoreVpnConnectionState(0xc4204b41d0, 0xc420029e30, 0x24, 0xc42001fed0, 0x1)
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/manager_switch.go:390 +0x94
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]: pkg.deepin.io/dde/daemon/network.(*switchHandler).enableVpn(0xc4204b41d0, 0xc420239301)
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/manager_switch.go:283 +0xbd
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]: pkg.deepin.io/dde/daemon/network.(*switchHandler).initPropVpnEnabled(0xc4204b41d0)
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/manager_switch.go:269 +0x7b
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]: pkg.deepin.io/dde/daemon/network.(*switchHandler).init(0xc4204b41d0)
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/manager_switch.go:71 +0x65
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]: pkg.deepin.io/dde/daemon/network.newSwitchHandler(0xc4204aea80, 0x55e0d3556d90)
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/manager_switch.go:39 +0x79
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]: pkg.deepin.io/dde/daemon/network.(*Manager).init(0xc4201c0900)
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/manager.go:183 +0x17b
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]: pkg.deepin.io/dde/daemon/network.(*Daemon).Start.func1()
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/main.go:91 +0x2f
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]: created by pkg.deepin.io/dde/daemon/network.(*Daemon).Start
Aug 04 07:06:53 myhostname com.deepin.dde.daemon.Dock[557]:         /build/deepin-daemon/src/dde-daemon-3.2.22/gopath/src/pkg.deepin.io/dde/daemon/network/main.go:90 +0x4f8
```

**Comment by felixonmars** [comment]
Is this issue still present on newer versions?

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
